name: Local Config
version: 1.0.0
schema: v1

models:
  - name: Qwen2.5 Coder
    provider: ollama
    model: qwen2.5-coder:7b-instruct-q4_K_M
    apiBase: http://localhost:11434
    roles:
      - chat
      - edit
      - apply

tabAutocomplete:
  model: Qwen2.5 Coder
  disable: true
