name: DeepSeek Config
version: 1.0.0
schema: v1

models:
  - name: DeepSeek-V3
    provider: openai
    model: deepseek-chat
    apiKey: "sk-bec27d3da65e47f39c33f67e9e2558b4"
    apiBase: https://api.deepseek.com/v1
    roles:
      - chat
      - edit
      - apply
      - autocomplete

tabAutocomplete:
  model: DeepSeek-V3